### ISSUE TITLE
Unresolved dependencies: org.scalaz.stream#scalaz-stream_2.11;0.7a: not found

### ISSUE THREAD

**Issue by chook** [tech-sketch/reactive-solar-farm-monitor#5]
even though it seems the bintray resolver is in place, when i do `activator solarFarmSimulator/run` I get:

[info] Resolving org.scalaz.stream#scalaz-stream_2.11;0.7a ...
[warn]     module not found: org.scalaz.stream#scalaz-stream_2.11;0.7a
[warn] ==== local: tried
[warn]   /root/.ivy2/local/org.scalaz.stream/scalaz-stream_2.11/0.7a/ivys/ivy.xml
[warn] ==== activator-launcher-local: tried
[warn]   /root/reactive-solar-farm-monitor/reactive-solar-farm-monitor/repository/org.scalaz.stream/scalaz-stream_2.11/0.7a/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/scalaz/stream/scalaz-stream_2.11/0.7a/scalaz-stream_2.11-0.7a.pom
[warn] ==== typesafe-releases: tried
[warn]   https://repo.typesafe.com/typesafe/releases/org/scalaz/stream/scalaz-stream_2.11/0.7a/scalaz-stream_2.11-0.7a.pom
[warn] ==== typesafe-ivy-releasez: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.scalaz.stream/scalaz-stream_2.11/0.7a/ivys/ivy.xml
[info] Resolving jline#jline;2.12.1 ...
[warn]     ::::::::::::::::::::::::::::::::::::::::::::::
[warn]     ::          UNRESOLVED DEPENDENCIES         ::
[warn]     ::::::::::::::::::::::::::::::::::::::::::::::
[warn]     :: org.scalaz.stream#scalaz-stream_2.11;0.7a: not found
[warn]     ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]     Note: Unresolved dependencies path:
[warn]         org.scalaz.stream:scalaz-stream_2.11:0.7a
[warn]           +- org.specs2:specs2-common_2.11:3.6
[warn]           +- org.specs2:specs2-matcher_2.11:3.6
[warn]           +- org.specs2:specs2-core_2.11:3.6
[warn]           +- org.specs2:specs2-junit_2.11:3.6
[warn]           +- com.typesafe.play:play-specs2_2.11:2.4.2 (/root/reactive-solar-farm-monitor/reactive-solar-farm-monitor/build.sbt#L103)
[warn]           +- reactive-solar-farm-monitor-testkit-akka:reactive-solar-farm-monitor-testkit-akka_2.11:0.2.0

**Comment by yugolf** [comment]
Sorry, you need add "scalaz-bintray" to resolvers.
Could you modify val of commonSettings (line 5 in build.sbt) as follows.

* build.sbt
```scala
lazy val commonSettings = Seq(
  version := "0.1.0",
  scalaVersion := "2.11.7",
  resolvers += "scalaz-bintray" at "http://dl.bintray.com/scalaz/releases"
)
```

**Comment by chook** [comment]
Awesome - I see the problem and fix!

I actually used a different workaround (~/.sbt/repositories)
